const departmentNames = [
    "Select department",
    "WATER MGMNT",
    "POLICE",
    "GENERAL SERVICES",
    "CITY COUNCIL",
    "STREETS & SAN",
    "OEMC",
    "AVIATION",
    "FIRE",
    "FAMILY & SUPPORT",
    "IPRA",
    "PUBLIC LIBRARY",
    "BUSINESS AFFAIRS",
    "TRANSPORTN",
    "HEALTH",
    "MAYOR'S OFFICE",
    "LAW",
    "FINANCE",
    "CULTURAL AFFAIRS",
    "COMMUNITY DEVELOPMENT",
    "BUILDINGS",
    "ANIMAL CONTRL",
    "CITY CLERK",
    "BOARD OF ELECTION",
    "INSPECTOR GEN",
    "TREASURER",
    "DISABILITIES",
    "HUMAN RESOURCES",
    "DoIT",
    "BUDGET & MGMT",
    "PROCUREMENT",
    "HUMAN RELATIONS",
    "BOARD OF ETHICS",
    "POLICE BOARD",
    "ADMIN HEARNG",
    "LICENSE APPL COMM"
];

export default departmentNames;
